### ISSUE TITLE
Factor out common packages to the top level package.json

### ISSUE THREAD

**Issue by mdial89f** [CMSgov/macpro-quickstart-serverless#113]
Common serverless packags (like plugin scripts, like termination protection) don't need to be installed in every service sub directory if they're instead added to the top level package.json/node_modules

Doing this will reduce the size of the deployment cache and reduce code overall. 

AC:
- Common packages are factored out into the top level package.json.
- Good sense was used in this endeavor.

**Comment by mdial89f** [comment]
When breaking serverless and its common plugins into the top level, the npm start command in the ui-src folder throws a dependency warning, and suggest setting SKIP_PREFLIGHT_CHECK=true to get around it.
I don't know if setting that is bad practice or not, or how to solve the real dep issue.
@macrael Any chance you're familiar with how to solve these?
For now I'm going to put this back in To-Do and we'll figure it out later.

**Comment by macrael** [comment]
We have on our backlog to investigate "yarn workspaces" they are supposed to help solve this problem.

**Comment by mdial89f** [comment]
This was closed in error... reopening
