### ISSUE TITLE
Introduce a single serverless deployment bucket

### ISSUE THREAD

**Issue by mdial89f** [CMSgov/macpro-quickstart-serverless#12]
By default, serverless creates a bucket for its use for each serivce.  This results in a lot of buckets.

It seems preferable to create a single bucket for all services use.  

AC:
- A single bucket for serverless deployments is shared by all services in a repo.

**Comment by mdial89f** [comment]
From Kristin:

Seven buckets per deployment kind of seems like a lot?
The following might be useful --

If you have defined multiple buckets, you can limit your deployment to a single bucket with the --bucket option:
$ sls s3deploy --bucket my-bucket
The ultimate goal is not running into that account bucket limit... it will help a lot to get moving to a CI where the destroy is automatically happening, but even with decent cleanup, it only takes 14 branches to blow the limit... I count 6 people already making branches, with at least 3 more onboarding this quarter...

Let's please optimize the bucket usage and cleanup :)

**Comment by kristin-at-theta** [comment]
kewl, yeah.... what this says

**Comment by mdial89f** [comment]
I'm having trouble tagging you
@kristin-at-theta

**Comment by mdial89f** [comment]
I guess it did tag you, it just didn't autofill :)

**Comment by mdial89f** [comment]
I've hesitated to do this ticket for a month or two now.  At the time, this seemed like a no brainer.
But I've held off on concerns of introducing shared infrastructure.

So right now, each serverless service is entirely independent of the others.  You can pick it up and move it and the other services could care less.
Using a single deployment bucket couples them at some level.  I'm not sure how much that hurts, but I just haven't seen enough of a reason to dip into the 'shared infra' territory yet.  

I agree, the 'destroy on branch delete' will help immensely.  That, and, macstack has lots of orphaned buckets from branches that were deleted in the old manner.  So a one-time clean up would help too.  We can also request an increase in bucket allotment.  

My position is:  this ticket isn't a good addition to the quickstart.  FWIW I'd recommend macstack do the mitigation steps above ^^^ (we can help), and pick up this issue if its a real problem.
tagging @kristin-at-theta and @sethsacher

**Comment by mdial89f** [comment]
Tagged wontfix and closing.  Notes above
