### ISSUE TITLE
Add draw.io architecture diagram

### ISSUE THREAD

**Issue by mdial89f** [CMSgov/macpro-quickstart-serverless#125]
## Type of Issue:

- [ ] Bug: Something isn't working
- [x] Enhancement: New feature or request
- [ ] Question: Further information is requested (I have a question)

#### Issue Creator Checklist

- [x] The appropriate label (bug, enhancement, question) has been attached to this issue.
- [x] This issue has been thoroughly documented below; a developer should be able to understand the issue by reading it.

## Background

There is a project wide push to move to draw.io for architecture diagrams.  Moving to an opensource diagramming solution should help enable anyone to update diagrams.
This issue is to add a draw.io architecture diagram of the quickstart to the repo.  The existing diagram is a static image export from LucidChart.  Copying and pasting the source file to draw.io should accomplish much of the work here.
Draw.io files are exported in XML.  It would be ideal if the draw.io export, when added to git, could be viewed from the README.  This would replace the need to have a static image checked in.
If the draw.io XML cannot be rendered from the README, the static image should still be removed.  It will undoubtedly fall out of date.  If this is the case, perhaps a github actions should publish the diagram on every push?  And a link in the README can take a user to where the diagram was published?
There's room to pick and choose here.  There's also static image editing, explained here: https://desk.draw.io/support/solutions/articles/16000042371-embed-a-diagram-in-github-markdown
The Pull Request template should be updated, too, with a checklist item for "I have updated the diagram if appropriate".

## Assorted Notes/Considerations

This is an implementation of work first done on BigMac.  See https://github.com/CMSgov/cms-bigmac/pull/38 for details.

## AC:

- An svg draw.io architecture diagram of the quickstart is added to the repository
- The existing .png diagram is removed
- A solution to directly render (in README) or link to the diagram is implemented.
- The pull request template is updated; a checklist item is added for updating the diagram, if appropriate.

**Comment by mdial89f** [comment]
This can be done concurrently with #131 since it will require updating the diagram.

**Comment by dwhitecl** [comment]
@ayoneeyee  I shared the existing diagram in diagrams.net with you please refer to this wiki page on how to modify and check in the diagram
https://qmacbis.atlassian.net/wiki/spaces/DSO/pages/1999765513/Environment+Diagram+Lifecycle

**Comment by mdial89f** [comment]
I had thought this was being worked/closed alongside #131 , but the current PR for the ES removal ( #162 ) only updates the .png file.  It does not add a draw.io svg.
I'm moving this back to To Do

**Comment by dwhitecl** [comment]
@ayoneeyee  reference the following confluence page with instructions to create an svg and import it to the repo
https://qmacbis.atlassian.net/wiki/spaces/DSO/pages/1999765513/Environment+Diagram+Lifecycle

**Comment by dwhitecl** [comment]
https://app.diagrams.net/#G1amPkNKdvsmVgOA42K6_pN-szR7QP1-aT
open this up 
remove ES
export as svg following instructions above
