### ISSUE TITLE
Add a GraphQL API to the application

### ISSUE THREAD

**Issue by mdial89f** [CMSgov/macpro-quickstart-serverless#150]
## Type of Issue:

- [x] Enhancement: New feature or request

#### Issue Creator Checklist

- [x] This issue has been thoroughly documented below; a developer should be able to understand the issue by reading it.

## Background

The MDCT team would like to start using GraphQL as part of the applications interaction with the Dynamo DB.  GraphQL offers the team a standard more "relational" syntax in interfacing with the DB (Its a specific API that does something very well and is becoming more widely adopted).  The purpose of this ticket is to incorporate graphql functionality into the quickstart app.

## Proposed Approach

Appsync is typically how we would resolve this issue. However, Appsync is not fedramp approved nor cms cloud approved. The time to get that approved and overhead involved is not feasible given the desired turnaround. 

The approach used elsewhere (specifically by the mc-review team) is to use Apollo server library running in lambda behind an App API and Apollo client library in the react code to interact with Apollo. 

Security for the App API we believe can be provided by the existing cognito user pool.

## Value

A standardized API call to the Dynamo DB for reading, writing, querying, etc.

## AC:
- Theres an App API for GraphQL 
- Lambdas will be created behind the API that utilize graphql to query the existing Dynamo
- The service will be protected by Cognito authentication 
- The GraphQL workflow will be utilized within the App itself (to be updated)
- Local workflow should be supported
- Update the quickstart environment diagram

**Comment by mdial89f** [comment]
@joeaero19 Please fill this out the best you can.

**Comment by joeaero19** [comment]
The following items have been completed
1. Graphql API
2. simple get query to retrieve uerId and User firstName
2. Cognito authentication has been implemented

TO DO:
1.  Change Apollo-lambda service name from Apollo-lambda to graphql
2. Create a search button for the graphql enpoint on the ui dashboard
3.   Local workflow should be supported
4.  Update the quickstart environment diagram

**Comment by mdial89f** [comment]
This issue is going to be closed without merge.  The work has been saved to the 'skipci-unfinished-graphql' branch.

The graphql infrastructure was easy enough, as was the react screens, but the LOE proved much higher than we thought, as no one available has a real understanding of graphql, it's virtues, or how it works.

Tagging as wontfix and deleting the branch with the CI build.  Again, the work will be pushed to a non-ci branch, 'skipci-unfinished-graphql', and protected; if you want/need this work, pull that branch

**Comment by mdial89f** [comment]
I'm also going to remove this from our QMR readiness milestone, as it's misleadingly juicing our stats in a positive way.
