### ISSUE TITLE
Documentation - Document SSM parameters used in operation

### ISSUE THREAD

**Issue by mdial89f** [CMSgov/macpro-quickstart-serverless#174]
## Type of Issue:

- [x] Enhancement: New feature or request

#### Issue Creator Checklist

- [x] This issue has been thoroughly documented below; a developer should be able to understand the issue by reading it.

## Background

This project has a fairly consistent approach to supplying the deploy/build with envirnoment specific information.
This pattern is typically referred to as our "SSM pattern".  #102 introduced this pattern; please see it for details.

In short, however, our "SSM pattern" utilizes [AWS Systems Manager Parameter Store ](https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-parameter-store.html) to hold environment specific information, both secret and non secret.

The serverless framework code will fetch information it needs from the serverless.yml

Example: https://github.com/CMSgov/macpro-quickstart-serverless/blob/master/services/app-api/serverless.yml#L32
In this example, we are setting the custom variable infrastructure type to one of the following, in this order:
- The value of /configuration/<current branch name>/infrastructure/type, if that parameter exists in SSM
- The value of /configuration/default/infrastructure/type, if that parameter exists in SSM
- Else, "development"

With this pattern, we can set a default (at /configuration/default/.....) to apply to all branches, but maintain the ability to override the default with /configuration/<current branch name/....

We use this pattern and this hierarchy in many places in the quickstart.  This issue is to document what SSM variables are used by the deployment.

## Proposed Approach

The most important aspect of this issue is to collect the existing possible SSM configurations.  The simplest option is to do this manually... go into each service, see what SSM params are in use, and document them somewhere.
An automated approach to collecting SSM params seems better, but is not a requirement here.

It's thought that having each service independently list its SSM options (maybe in the serverless.yml, or maybe in a README.md inside each service) is good.

Listing them all together in the top level README might also be good.

These are just ideas.

## Value

Consumers of the quickstart will have a list of SSM parameters used by the deployment, and should have an easier experience forking and setting up their project.

## AC:

- All SSM parameters used by the deployment are documented in a sensible fashion.

**Comment by joeaero19** [comment]
All ssm parameters used in ech of the services have been added as a comment at the top of each of the services serverless.yml file. The services that got modified are:
 
app-api, stream-functions,ui-auth,ui,uploads.
