### ISSUE TITLE
Add unit testing

### ISSUE THREAD

**Issue by mdial89f** [CMSgov/macpro-quickstart-serverless#176]
## Type of Issue:

- [x] Enhancement: New feature or request

#### Issue Creator Checklist

- [ ] This issue has been thoroughly documented below; a developer should be able to understand the issue by reading it.

## Background

to be updated later but adding in some temp notes:
This ticket is largely for incorporating unit testing processes into the pipeline. This will be for adding a simple unit test to the existing application and it will run on code push. 

## Proposed Approach

The existing [test steps](https://github.com/CMSgov/macpro-quickstart-serverless/blob/master/.github/workflows/deploy.yml#L77-L88) in the Deploy workflow essentially run  nightwatch.  A top level test.sh script is a simple runner.

Incorporating a unit test stage should probably follow similar pattern.  A new unit-test.sh script could be made, or perhaps piggyback on the existing.  Off hand, it seems having a separate script/workflow to call the unit testing bit is better.  The unit tests probably want to run before deployment, so a separate script makes sense.

This script might operate much like deploy.sh... iterating over the list of services and running a standard test command in each.  

Jest seems to be the default choice here.

## Value

Having a unit test step incorporated into the quickstarts Deploy workflow demonstrates a pattern for how and when unit tests get run.  Consumers of this project should have a clearer picture of how to extend or modify the unit test coverage.

## AC:

- A unit test is added to at least one service.
- The unit tests are run as part of the Deploy workflow on each push.

**Comment by dwhitecl** [comment]
added this functionality to the SEDS repo yesterday and this morning, will be pulling much of that back to the quickstart now 
https://github.com/CMSgov/cms-mdct-seds/pull/253
