### ISSUE TITLE
Publish code coverage metrics to the README

### ISSUE THREAD

**Issue by mdial89f** [CMSgov/macpro-quickstart-serverless#184]
## Type of Issue:

- [x] Enhancement: New feature or request

#### Issue Creator Checklist

- [ ] This issue has been thoroughly documented below; a developer should be able to understand the issue by reading it.

## Background

This should follow #176 

Once unit testing (however minimal) is in place, the code coverage percentage should be published in an easily viewable location.
The existing idea is to add a badge to the README (see top of the README.md) that fetches the published coverage percentage.

## Proposed Approach

Dynamic build badges are a thing.  If our CI pipeline for master publishes a code coverage percentage, a build badge should be able to display whatever that value is.  

## Value

Understanding the code coverage percentage for the project is simple and immediate when visiting the project repo.

## AC:

- The code coverage percentage is displayed on the project home page.

**Comment by dwhitecl** [comment]
issue was closed as part of work done in 
https://github.com/CMSgov/macpro-quickstart-serverless/pull/199
