### ISSUE TITLE
Remove running nightwatch tests in non development environments 

### ISSUE THREAD

**Issue by dwhitecl** [CMSgov/macpro-quickstart-serverless#192]
## Type of Issue:

- [x] Bug: Something isn't working

#### Issue Creator Checklist

- [x ] This issue has been thoroughly documented below; a developer should be able to understand the issue by reading it.

## What's broken?

Currently nightwatch frontend tests are running in our "val" and "prod" environments. We do not want that to occur.  We should have a mechanism in place to disable those runs in meaningful environments.

## What's the impact of this bug?

Nightwatch tests are currently broken and exposed this issue. If we rolled the quickstart out to a team tests would run in environments that we do not want to run tests in so we should get ahead of that issue.

## Steps to Reproduce?

see example of failed nightwatch test in the production deploy
https://github.com/CMSgov/macpro-quickstart-serverless/actions/runs/775061883

## Assorted Notes/Considerations

Here is how the issue was resolved in the macstack repository
https://github.com/CMSgov/macstack-spa-submission-form/blob/develop/.github/workflows/deploy.yml#L124-L130

## AC:

nightwatch will no longer run in the val and prod environments.

**Comment by mdial89f** [comment]
- I think a larger conversation around testing posture should be had.  
- In my opinion, all tests should run against production as a rule, with exceptions made for tests that are valuable but for some reason can't run against prod.
- Our current tests should all run against production, as it's all non-destructive smoke testing.
- This should be an enhancement if/when reopened.

**Comment by joeaero19** [comment]
The job was failing because the chromedriver was outdated. The chrome driver was upgraded and the jobs are fixed.
