### ISSUE TITLE
Add Getting Started to the Wiki documentation from developer POV

### ISSUE THREAD

**Issue by mdial89f** [CMSgov/macpro-quickstart-serverless#229]
## Type of Issue:

- [x] Enhancement: New feature or request

#### Issue Creator Checklist

- [x] This issue has been thoroughly documented below; a developer should be able to understand the issue by reading it.

## Background

The quickstart is lacking in documentation from two points of view:
- a deeloper working on a project that forked from the quickstart
- an admin that is forking this project to start a new one

This ticket is to address the first scenario... a developer working on this project.  Specifically, this issue is to add an end to end guide a developer would use to go from "i have a mac and write permissions on the repo" to "i am configured to run locally and work issues."

## Proposed Approach

This guidance document should include - or sew together - technical prerequisites and how-to guides to get functional.  A developer in the blind should be able to follow along and be setup for development and work issues.

The github wiki seems like the logical home for this document, although it's suggested we put a pointer/reference in the top level README that points new devs to the wiki.

The output of this issue is an end to end guide, but there will undoubtedly be new how-to's and installation guides to be written.  So have been written, some still left.  A non-comprehensive (please feel free to add) list of setup steps include:
- cloning the repo
- how to install brew
- installing node
- installing nvm
- installing awscli
- getting aws access keys (cloudtamer is a subset here)
- how-to tail awslogs
- running the "./dev local" workflow
- how-to run react locally tied to the cloud (explanation warranted here)
- how-to install and run 'codeclimate analyze'

## Value

New developers will have an easy and complete guide to install prerequisites and start working.

## AC:

- Documentation is produced as described above.

**Comment by joeaero19** [comment]
The documents have been provided for these items at the wiki section of this repo:

cloning the repo
how to install brew
installing node
installing nvm
installing awscli
getting aws access keys (cloudtamer is a subset here)
how-to tail awslogs
running the "./dev local" workflow
how-to run react locally tied to the cloud (explanation warranted here)
how-to install and run 'codeclimate analyze'
