### ISSUE TITLE
Add sample ssm parameters to documentation 

### ISSUE THREAD

**Issue by dwhitecl** [CMSgov/macpro-quickstart-serverless#282]
## Type of Issue:

- [x] Enhancement: New feature or request

#### Issue Creator Checklist

- [ x] This issue has been thoroughly documented below; a developer should be able to understand the issue by reading it.

## Background

Currently each service within the app has a README which documents the ssm parameters associated with that service.  See example: https://github.com/CMSgov/macpro-quickstart-serverless/blob/master/services/app-api/README.md

As an enhancement to this documentation we should provide a sample ssm parameter column to provide more clear direction to consumers of the quickstart.

## Proposed Approach

create new column in each service README.md and populate that column with sample SSM parameters redacting any sensitive or account specific values.  

## Value

Provides clear direction to consumers looking to get setup with minimal hand holding

## AC:

Each service will have the README.md updated appropriately and no sensitive or account specific values will appear in the documentation.

**Comment by joeaero19** [comment]
All documentation has been completed.
