### ISSUE TITLE
Bucket versioning broke destroy functionality

### ISSUE THREAD

**Issue by mdial89f** [CMSgov/macpro-quickstart-serverless#285]
## Type of Issue:

- [x] Bug: Something isn't working

#### Issue Creator Checklist

- [x] This issue has been thoroughly documented below; a developer should be able to understand the issue by reading it.

## What's broken?

The destroy script no longer works as intended.  While the script succeeds, the underlying cloudformation stacks fail to destroy, as underlying S3 buckets are not empty.  
There is an existing piece of logic in the destroy script that empties bucket of all objects, but it does not account for any versions or delete markers in buckets with versioning enabled.

## What's the impact of this bug?

Cloudformation stacks are silently failing to destroy, as their underlying S3 buckets are no longer being emptied properly since the advent of bucket versioning.

## Steps to Reproduce?

Run the destroy script against any environment built since versioning was enabled.

## Assorted Notes/Considerations

N/A

## AC:

- Destroy script functionality is working.
- All Cloudformation stages for the target stage are removed as expected.

**Comment by macrael** [comment]
Was this fixed by #286 ? can it be closed?

**Comment by mdial89f** [comment]
> Was this fixed by #286 ? can it be closed?

Yeah for sure.  I'm not sure why #286 didn't auto-close this... I see the closing language in the PR.  Maybe that closing language was added after the merge?  

Closing.  Thanks @macrael
