### ISSUE TITLE
Point to (new) remote plugin repos

### ISSUE THREAD

**Issue by mdial89f** [CMSgov/macpro-quickstart-serverless#300]
## Type of Issue:

- [x] Enhancement: New feature or request

#### Issue Creator Checklist

- [x] This issue has been thoroughly documented below; a developer should be able to understand the issue by reading it.

## Background

Currently, we have three plugins in a to level plugins directory.  Our package.json specifies these plugins as a dev dependency.  Instead of specifying a version to fetch and install from npm, the package.json points to the local file path of the plugin source.

We now want to move the three plugins into three new repositories, each having its own.  This will allow this project and other projects to use these plugins without having the plugins' source code copied into each repo.

The plan is to first move these plugins to their own repos.  Then, update the quickstart's package.json (and yarn.lock) to install the plugins from git following [git url as dependency format](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#git-urls-as-dependencies).  Eventually, we'd like to see these projects publish to npm with automated semver support, but pointing package.json's to a git repo is a good first step.

## Proposed Approach

As stated somewhat in the background section, the proposed approach is:
- Move the current plugins' source code to their respective repositories.  This work is tracked and accomplished outside the scope of this repo, however it will likely be done by whoever picks up this ticket.  Consider this a prereq to this ticket.
- Update any package.json (and yarn.lock) that points to the local 'plugins' directory to instead fetch/install plugins from the newly created plugin repos, following [git dependency url format](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#git-urls-as-dependencies).
- Remove the plugins directory from this repository, as it is no longer needed.
- Create a PR and follow standard merge procedures.
- Be ready with a plan to disseminate this ticket to consumer groups, current and future (macstack, mcr, etc).

## Value

This changeset accompanied by moving the plugins into their own repositories makes the plugins much easier to consume.

## Notes, assorted:

- This ticket doesn't detail how to move code to those repos, and doesn't care to.  But in the event the person reading this ticket is about to move code to those new repos, please note in those repos that until strict semver and publishing support is in place, extreme caution should be used when updating any of those plugins, as there are will be an unknown (and assumed 'n') number of consumers.
- The new repos:
https://github.com/CMSgov/serverless-s3-bucket-helper
https://github.com/CMSgov/serverless-idempotency-helper
https://github.com/CMSgov/serverless-iam-helper

## AC:

- The plugins source code is removed from this repository.
- All package.json (and yarn.lock) files are updated to fetch/install the plugins from their remote git repos instead of the local source folder.

**Comment by joeaero19** [comment]
The plugin source codes were moved to their respective repositories  (https://github.com/CMSgov/cms-serverless-iam-helper, https://github.com/CMSgov/cms-serverless-idempotency-helper, https://github.com/CMSgov/cms-serverless-s3-bucket-helper )

All package.json (and yarn.lock) files are updated to fetch/install the plugins from their remote git repos instead of the local source folder.

The plugins source code is removed from this repository.

PR ( https://github.com/CMSgov/macpro-quickstart-serverless/pull/306) has been created.
