### ISSUE TITLE
Add WAF logging

### ISSUE THREAD

**Issue by mdial89f** [CMSgov/macpro-quickstart-serverless#50]
The WAF logs for Cloudfront and APIGW should be piped to S3 for storage and analysis.  This should allow for insights into what requests are getting denied, what ips are hammering the sight... take your pick.

AC:
- The WAF logs from Cloudfront and APIGW are collected and stored in S3.

**Comment by dwhitecl** [comment]
@joeaero19 @mdial89f  
This actually is closed. Can we address pointing to that PR in this ticket and document it accordingly?

**Comment by mdial89f** [comment]
Assigning to you @joeaero19 since you did the work.

**Comment by mdial89f** [comment]
@joeaero19

**Comment by joeaero19** [comment]
This ticket was split into 2 issues. Issue 1 was to create the s3 bucket that will hold the logs and issue 2 was to enable waf logging and ship the logs to the s3 bucket in issue one by using firehose. for further details on the issues and the PR, please refer to the links below.



issue1: https://github.com/CMSgov/macpro-quickstart-serverless/issues/120
PR:       https://github.com/CMSgov/macpro-quickstart-serverless/pull/121

issue2: https://github.com/CMSgov/macpro-quickstart-serverless/issues/122
PR:       https://github.com/CMSgov/macpro-quickstart-serverless/pull/97
