### ISSUE TITLE
Git Actions deployment uses set-env, which is deprecated

### ISSUE THREAD

**Issue by kristin-at-theta** [CMSgov/macpro-quickstart-serverless#92]
Eventually that's gonna bite... so at least we'll capture it here?  While I was PR-ing the branch to move to Actions, I poked around to see if it was easy enough for me to "just update". and..... when less is at stake, I will update and test, though I am happy to let you someone else do this, too :)

**The `set-env` command is deprecated and will be disabled soon:**
`A moderate security vulnerability has been identified in the GitHub Actions runner that can allow environment variable and path injection in workflows that log untrusted data to stdout. This can result in environment variables being introduced or modified without the intention of the workflow author. To address this issue we have introduced a new set of files to manage environment and path updates in workflows.`

**Here's what I found as a solution:**
Setting an environment variable
echo "{name}={value}" >> $GITHUB_ENV

Creates or updates an environment variable for any actions running next in a job. The action that creates or updates the environment variable does not have access to the new value, but all subsequent actions in a job will have access. Environment variables are case-sensitive and you can include punctuation.

Example
echo "action_state=yellow" >> $GITHUB_ENV
Running $action_state in a future step will now return yellow

Multline strings
For multiline strings, you may use a delimiter with the following syntax.

{name}<<{delimiter}
{value}
{delimiter}
Example
In this example, we use EOF as a delimiter and set the JSON_RESPONSE environment variable to the value of the curl response.

steps:
  - name: Set the value
    id: step_one
    run: |
        echo 'JSON_RESPONSE<<EOF' >> $GITHUB_ENV
        curl https://httpbin.org/json >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
Adding a system path
echo "{path}" >> $GITHUB_PATH

Prepends a directory to the system PATH variable for all subsequent actions in the current job. The currently running action cannot access the new path variable.

Example
echo "/path/to/dir" >> $GITHUB_PATH

**Comment by mdial89f** [comment]
Duplicate of #72 
Feel free to copy/paste over there!

**Comment by kristin-at-theta** [comment]
Darn!  I thought this meant it was done!!!!! *small sigh*
